# Generated by Django 4.1.6 on 2023-02-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platos',
            name='nombre',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platos',
            name='precio',
            field=models.FloatField(default=0),
        ),
    ]
